#!/bin/bash

echo ""
echo "### FFdecsa optimization helper/benchmark "
echo "### Version 10"
echo ""
echo ""

# customize here
FFdecsaDIR="./FFdecsa"
OwnFlags=""

# compiler
CC=$CCC

# some initial values
OLevel=""
PMode=""
MTimes=10

_FLAGS=""
_CPU=""
_VERB=1
_SHORT=1
_NOTEST=0
_CANNAT=0
_NONAT=0
_DONAT=0

print_usage() {
  echo ""
  echo "Usage: $0 [OPTION [ARG]]..."
  echo ""
  echo "Options:"
  echo "-D [PATH]     path to FFdecsa source directory"
  echo "-O [LEVEL]    set custom optimization level e.g. S, 2 or 3"
  echo "-P [MODE]     test only the given PARALLEL_MODE"
  echo "-T [N]        number of tests per mode"
  echo "-e            extended - test all PARALLEL_MODEs"
  echo "-q            be quiet - only results, warnings and errors"
  echo "-h            this output"
  echo ""
}


while getopts "D:O:P:T:eqh" options; do
  case $options in
    D ) if [ -d $OPTARG ]; then
          FFdecsaDIR=$OPTARG
        fi
        ;;
    O ) if [ -n $OPTARG ]; then
          OLevel=$OPTARG
        fi
        ;;
    P ) if [ -n $OPTARG ]; then
          PMode=$OPTARG
        fi
        ;;
    T ) if [[ $OPTARG =~ ^[0-9]+$ ]]; then
          MTimes=$OPTARG
        fi
        ;;
    e ) _SHORT=0
        ;;
    q ) _VERB=0
        ;;
    h ) print_usage
        exit 0
        ;;
   \? ) print_usage
        exit 1;;
  esac
done

if [ "$OLevel" != "" ]; then
  case $OLevel in
    S|s) OptFlag="-Os";;
    0)   OptFlag="-O0";;
    1)   OptFlag="-O1";;
    2)   OptFlag="-O2";;
    3)   OptFlag="-O3";;
    *)   OptFlag="-O2";;
  esac
fi

source_check() {
  testpath=$1
  if [ -f "${testpath}/FFdecsa.c" ] && [ -f "${testpath}/FFdecsa_test.c" ]; then
    return 0
  else
    return 1
  fi
}

[ -z "$CC" ] && CC=g++

try_gcc_options() {
    $CC $* -S -o /dev/null -xc /dev/null >/dev/null 2>&1
}

if ! try_gcc_options; then
    echo "Error: Couldn't execute your compiler ($CC)" >&2
    exit 1
fi

if try_gcc_options -march=i386; then
    is_x86_64=0
else
    is_x86_64=1
fi

read_cpu_data_linux() {
    IFS=":"
    while read name value; do
        unset IFS
        name=`echo $name` #strip spaces
        if [ "$name" != "flags" ]; then
            value=`echo $value | sed 's/\([^ ]*\).*/\1/'` #take first word
        fi
        IFS=":"
        if [ "$name" = "vendor_id" ]; then
            vendor_id="$value"
        elif [ "$name" = "cpu family" ]; then
            cpu_family="$value"
        elif [ "$name" = "model" ]; then
            cpu_model="$value"
        elif [ "$name" = "flags" ]; then
            flags="$value"
            break #flags last so break early
        fi
    done < /proc/cpuinfo
    unset IFS
}

read_cpu_data() {
    # Default values
    vendor_id="NotFound"
    cpu_family="-1"
    cpu_model="-1"
    flags=""
    read_cpu_data_linux
}

read_cpu_data

# look if "native" flag is supported
if try_gcc_options "-march=native"; then
  _CANNAT=1
fi

if [ $_VERB -ge 1 ]; then
    gcc_ver=`$CC -v 2>&1 | grep -i "gcc version" | head -n 1`
    
    echo "### CPU-INFO ###"
    if [ $is_x86_64 -eq 0 ]; then
      echo "System: x86"
    else
      echo "System: x86_64"
    fi
    echo ""
    echo "Vendor-ID: $vendor_id"
    echo "CPU-Family: $cpu_family"
    echo "CPU-Model: $cpu_model"
    echo "Flags: $flags"
    echo ""
    echo "$gcc_ver"
fi

if [ $_CANNAT -ge 1 ] && [ $_NONAT -eq 0 ]; then
  _DONAT=1
  _CPU="native"
  if [ $_VERB -ge 1 ]; then
    echo "Using compilers \"native\" flags"
    echo ""
  fi
fi

if [ $is_x86_64 -eq 1 ]; then
    if [ "$_FLAGS" != "" ]; then
        _FLAGS="$_FLAGS -fPIC"
    else
        _FLAGS=" -fPIC"
    fi
fi

# complete flags for FFdesca_Test
if [ "$OwnFlags" != "" ]; then
  IFLAGS=$OwnFlags
elif [ "$OLevel" == "" ]; then
  IFLAGS="-march=${_CPU}${_FLAGS} -fexpensive-optimizations -fomit-frame-pointer -funroll-loops"
else
  IFLAGS="$OptFlag -march=${_CPU}${_FLAGS} -fexpensive-optimizations -fomit-frame-pointer -funroll-loops"
fi


###
### FFdecsa Test - get best PARALLEL_MODE
###

ffdecsa_test() {

  if [ "$PMode" == "" ]; then
    if [ $_SHORT -lt 1 ]; then
      FFDECSA_MODES="PARALLEL_32_INT PARALLEL_32_4CHAR PARALLEL_32_4CHARA \
                     PARALLEL_64_8CHAR PARALLEL_64_8CHARA PARALLEL_64_2INT \
                     PARALLEL_64_LONG PARALLEL_64_MMX PARALLEL_128_16CHAR \
                     PARALLEL_128_16CHARA PARALLEL_128_4INT PARALLEL_128_2LONG \
                     PARALLEL_128_2MMX PARALLEL_128_SSE PARALLEL_128_SSE2"
    else
      FFDECSA_MODES="PARALLEL_64_MMX PARALLEL_128_2MMX \
                     PARALLEL_128_SSE PARALLEL_128_SSE2"
    fi
  else
    FFDECSA_MODES=$PMode
  fi

  if test "x${TMPDIR}" = "x"; then
    TMPDIR="/tmp/FFdecsa"
  fi

  if [ -d "${TMPDIR}" ]; then
    rm -rf "${TMPDIR}"
  fi
  
  mkdir "${TMPDIR}"
  TMPOUT="${TMPDIR}/out"

  cp $FFdecsaDIR/*.c $FFdecsaDIR/*.h $FFdecsaDIR/Makefile "${TMPDIR}"

  if [ "$OwnFlags" != "" ]; then
    FLAGS="$IFLAGS"
  else
    FLAGS="$1 $IFLAGS"
  fi 

  COMPILER=$CC
  export FLAGS
  export COMPILER

  for var in ${FFDECSA_MODES}; do
    if [ $_VERB -ge 1 ]; then
      echo "    ${var}"
    fi
    make -C "${TMPDIR}" -e FFdecsa_test "PARALLEL_MODE=${var}" >/dev/null 2>&1
    if test $? -ne 0 ; then
      if [ $_VERB -ge 1 ]; then
        echo "    ${var}: build failed"
      fi
    else
      MAX_M_val=0
      rm -f ${TMPOUT}
      sync;sleep 2; "${TMPDIR}/FFdecsa_test" > /dev/null 2>"${TMPOUT}"
      if test $? -ne 0; then
        if [ $_VERB -ge 1 ]; then
          echo "    ...failed!"
        fi
      else
        grep FAILED "${TMPOUT}" >/dev/null 2>&1
        if test $? -ne 1; then
          if [ $_VERB -ge 1 ]; then
            echo "    ...failed!"
          fi
        else
          MAX_M_val=`grep "speed=.*Mbit" "${TMPOUT}" | sed -e 's/^.*=\([0-9]*\)\.[0-9]* Mbit.*$/\1/'`
          if [ $_VERB -ge 1 ]; then
            printf "      - $MAX_M_val"
          fi
          
          if [ $MTimes -ge 2 ]; then
            for i in `seq 2 $MTimes`; do
              # sync;
              # sleep 1; 
              "${TMPDIR}/FFdecsa_test" > /dev/null 2>"${TMPOUT}"
              res=`grep "speed=.*Mbit" "${TMPOUT}" | sed -e 's/^.*=\([0-9]*\)\.[0-9]* Mbit.*$/\1/'`
              if test $res -gt $MAX_M_val; then
                MAX_M_val=$res
              fi
              if [ $_VERB -ge 1 ]; then
                printf ", $res"
              fi
            done
          fi

          if [ $_VERB -ge 1 ]; then
            printf "\n"
            echo "      - $MAX_M_val Mbit/s max."
          fi

          if [ "$1" == "-O2" ]; then          
            if test $MAX_M_val -gt $MAX_val_2; then
              MAX_val_2=$MAX_M_val
              MAX_MODE_2=$var
              MAX_val=$MAX_M_val
              MAX_MODE=$var
            fi
          elif [ "$1" == "-O3" ]; then
            if test $MAX_M_val -gt $MAX_val_3; then
              MAX_val_3=$MAX_M_val
              MAX_MODE_3=$var
              MAX_val=$MAX_M_val
              MAX_MODE=$var
            fi
          elif test $MAX_M_val -gt $MAX_val; then
            MAX_val=$MAX_M_val
            MAX_MODE=$var
          fi

        fi
      fi
    fi

    make -C "${TMPDIR}" clean >/dev/null 2>&1

  done

  unset

  if [ $_VERB -ge 1 ]; then
    echo "  Fastest PARALLEL_MODE = ${MAX_MODE} (${MAX_val} Mbit/s)"
    echo ""
  fi

  rm -rf "${TMPDIR}"
}

MAX_val=0
MAX_val_2=0
MAX_val_3=0
MAX_MODE="PARALLEL_64_MMX"
MAX_MODE_2="PARALLEL_64_MMX"
MAX_MODE_3="PARALLEL_64_MMX"

if [ $_NOTEST -eq 0 ]; then

  if [ $_VERB -ge 1 ]; then
      echo "### FFdeCSA TEST ###"
      echo "Using compiler: $CC"
      echo "Flags: $IFLAGS"
      echo ""
  fi

  if [ "$OwnFlags" != "" ]; then
    ffdecsa_test
  elif [ "$OLevel" != "" ]; then
    ffdecsa_test "$OptFlag"
  else
    if [ $_VERB -ge 1 ]; then
      echo "Testing optimization levels 2 and 3"
      echo ""
      echo "This may take a while...

Please be patient"
      echo ""
    else
      echo "This may take a while..."
    fi
    for i in `seq 2 3`; do
      if [ $_VERB -ge 1 ]; then
        echo "  Level -O${i}:"
      fi
      ffdecsa_test "-O${i}"
    done
    if [ $MAX_val_3 -ge $MAX_val_2 ]; then
      MAX_MODE=$MAX_MODE_3
      MAX_val=$MAX_val_3
      OptFlag="-O3"
    else
      MAX_MODE=$MAX_MODE_2
      MAX_val=$MAX_val_2
      OptFlag="-O2"
    fi
    echo ""
    echo "Best result with $OptFlag and $MAX_MODE at $MAX_val Mbit/s"
    echo ""
    echo ""
  fi
fi

echo "### FFdeCSA Fasted OPTS ###"

echo "CPUOPT     ?= $_CPU"
if [ $_NOTEST -eq 0 ]; then
  echo "PARALLEL   ?= $MAX_MODE"
else
  echo "PARALLEL   ?= $MAX_MODE   # untested!"
fi
if [ "$_FLAGS" == "" ]; then
  echo "CSAFLAGS   ?= $OptFlag -fexpensive-optimizations -fomit-frame-pointer -funroll-loops"
else
  echo "CSAFLAGS   ?= ${OptFlag}${_FLAGS} -fexpensive-optimizations -fomit-frame-pointer -funroll-loops"
fi
echo "### GENERIC FFdeCSA make OPTS ###"


if [ "$OwnFlags" != "" ] || [ "$OLevel" != "" ]; then
  echo "FFDECSA_OPTS = \"FLAGS=${IFLAGS}\" PARALLEL_MODE=${MAX_MODE} COMPILER=$CC" >> config.mak
else
  echo "FFDECSA_OPTS = \"FLAGS=$OptFlag ${IFLAGS}\" PARALLEL_MODE=${MAX_MODE} COMPILER=$CC" >> config.mak
fi
echo ""

exit 0

