#! /bin/sh
### BEGIN INIT INFO
# Provides:          mythtv-backend
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      mysql
# Should-Stop:       mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop the MythTV server.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/mythbackend
NAME="mythbackend"
DESC="MythTV server"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

set -e


USER=mythtv
USER_HOME=$(grep ^$USER /etc/passwd | awk -F : '{print $6}')
RUNDIR=/var/run/mythtv
LOGDIR=/var/log/mythtv
ARGS_BASIC="--daemon --logpath $LOGDIR --pidfile $RUNDIR/$NAME.pid"
ARGS_EXTRA=""
NICE=0

if [ -f /etc/default/mythtv-backend ]; then
  . /etc/default/mythtv-backend
fi

ARGS="$ARGS_BASIC $ARGS_EXTRA"

mkdir -p $LOGDIR
chown -R $USER $LOGDIR
mkdir -p $RUNDIR
chown -R $USER $RUNDIR

unset DISPLAY
unset SESSION_MANAGER

case "$1" in
  start)
	if test -e $RUNDIR/$NAME.pid ; then
		echo "mythbackend already running, use restart instead."
	else
                test -f /etc/default/locale && . /etc/default/locale || true
                rm -f /var/log/mythtv/* > /dev/null 2>&1
		echo "Starting $DESC: $NAME"
		start-stop-daemon --start --chuid $USER --nicelevel $NICE --exec $DAEMON -- $ARGS
	fi
	;;
  stop)
	echo "Stopping $DESC: $NAME"
	start-stop-daemon --stop --oknodo --chuid $USER --exec $DAEMON -- $ARGS
	test -e $RUNDIR/$NAME.pid && rm $RUNDIR/$NAME.pid
	;;
  restart|force-reload)
	echo "Restarting $DESC: $NAME"
	start-stop-daemon --stop --oknodo --chuid $USER --exec $DAEMON -- $ARGS
	sleep 3
        test -f /etc/default/locale && . /etc/default/locale || true
	start-stop-daemon --start --chuid $USER --nicelevel $NICE --exec $DAEMON -- $ARGS
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

